In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('input', header=None)

In [3]:
data

0
0    .......12.......935............184.720...243.....
1    ......*.....968*.....$............*........=.....
2    ....291............612....290..........903.......
3    ..............156......$..*...891.&731....%..8...
4    ................*...189..591.*...................
..                                                 ...
135  ....*.....=................+.........76..328.....
136  ...........254........../...........*...*........
137  .96....990.........%..718...%....869.......596...
138  ...*....*........=.86.....499..............*.....
139  ...780.685.....822....................560.35.....

[140 rows x 1 columns]

In [4]:
lol = []
for line in data[0]:
    lol.append([char for char in line])

In [5]:
np.unique(lol)

array(['#', '$', '%', '&', '*', '+', '-', '.', '/', '0', '1', '2', '3',
       '4', '5', '6', '7', '8', '9', '=', '@'], dtype='<U1')

In [6]:
# find the locations of "characters"

char_coords = []

chars = '#$%&*+-/=@'

for i in range(len(lol)):
    for j in range(len(lol[0])):
        if lol[i][j] in chars:
            char_coords.append((i,j))


In [7]:
char_coords

[(1, 6),
 (1, 15),
 (1, 21),
 (1, 34),
 (1, 43),
 (1, 52),
 (1, 70),
 (1, 97),
 (1, 125),
 (1, 132),
 (2, 62),
 (2, 92),
 (2, 108),
 (2, 120),
 (3, 23),
 (3, 26),
 (3, 34),
 (3, 42),
 (3, 86),
 (3, 99),
 (3, 114),
 (3, 133),
 (4, 16),
 (4, 29),
 (4, 46),
 (4, 67),
 (4, 79),
 (4, 102),
 (4, 128),
 (5, 6),
 (5, 57),
 (5, 61),
 (5, 116),
 (6, 35),
 (6, 51),
 (6, 65),
 (6, 109),
 (7, 73),
 (7, 84),
 (7, 101),
 (7, 113),
 (7, 118),
 (7, 122),
 (7, 128),
 (8, 4),
 (8, 15),
 (8, 19),
 (8, 27),
 (8, 54),
 (8, 64),
 (8, 136),
 (9, 30),
 (9, 38),
 (9, 95),
 (9, 109),
 (9, 118),
 (10, 6),
 (10, 14),
 (10, 43),
 (10, 77),
 (10, 93),
 (10, 123),
 (10, 131),
 (11, 22),
 (11, 53),
 (11, 106),
 (12, 3),
 (12, 28),
 (12, 48),
 (12, 72),
 (12, 87),
 (12, 110),
 (12, 128),
 (13, 10),
 (13, 35),
 (13, 40),
 (13, 67),
 (13, 78),
 (13, 93),
 (13, 113),
 (14, 19),
 (14, 38),
 (14, 61),
 (15, 15),
 (15, 28),
 (15, 52),
 (15, 89),
 (15, 97),
 (15, 134),
 (16, 6),
 (16, 26),
 (16, 33),
 (16, 41),
 (16, 43),
 (1

In [8]:
arr = np.array(lol)

In [9]:
mask = np.zeros(np.array(lol).shape)

In [10]:
for cc in char_coords:
    for i in np.arange(-1,2):
        for j in np.arange(-1,2):
            mask[cc[0]+i, cc[1]+j] = 1

In [11]:
mask

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [12]:
np.where(mask > 0)

(array([  0,   0,   0, ..., 139, 139, 139]),
 array([  5,   6,   7, ..., 134, 135, 136]))

In [13]:
grow_mask = mask*0

In [14]:
digits = ['%i' % i for i in np.arange(10)]

for dig in ['%i' % i for i in np.arange(10)]:
    grow_mask[np.where((mask > 0) & (arr == dig))] = 1

In [15]:
grow_mask


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
previous_sum = -1
while np.sum(grow_mask) != previous_sum:
    previous_sum = np.sum(grow_mask)
    for i,row in enumerate(grow_mask):
        hit = np.where(row > 0)[0]
        ahead = hit+1
        ahead = ahead[np.where(ahead < len(lol[0]))]
        for check in ahead:
            if lol[i][check] in digits:
                grow_mask[i,check] = 1

        ahead = hit-1
        ahead = ahead[np.where(ahead > -1)]
        
        for check in ahead:
            if lol[i][check] in digits:
                grow_mask[i,check] = 1
    


In [17]:
grow_mask

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [18]:
arr[np.where(grow_mask == 0)] = ' '

In [19]:
numbers = []
for row in arr:
    row_str = ''
    for char in row:
        row_str += char
    blobs = row_str.split(' ')
    for blob in blobs:
        if blob != '':
            numbers.append(int(blob))

In [20]:
numbers

[12,
 935,
 184,
 720,
 243,
 589,
 435,
 6,
 904,
 968,
 986,
 459,
 422,
 482,
 291,
 612,
 290,
 903,
 699,
 218,
 376,
 890,
 838,
 81,
 138,
 194,
 156,
 891,
 731,
 89,
 523,
 699,
 227,
 225,
 388,
 189,
 591,
 783,
 107,
 533,
 909,
 603,
 424,
 229,
 952,
 938,
 470,
 555,
 746,
 28,
 279,
 826,
 788,
 867,
 102,
 542,
 779,
 182,
 166,
 511,
 727,
 282,
 237,
 171,
 892,
 989,
 709,
 8,
 974,
 873,
 129,
 491,
 877,
 715,
 270,
 53,
 781,
 295,
 773,
 336,
 547,
 800,
 359,
 342,
 468,
 573,
 850,
 465,
 192,
 115,
 988,
 731,
 789,
 673,
 256,
 677,
 621,
 716,
 910,
 297,
 204,
 69,
 905,
 641,
 472,
 524,
 127,
 714,
 62,
 324,
 812,
 955,
 257,
 545,
 668,
 91,
 840,
 566,
 66,
 660,
 469,
 525,
 25,
 666,
 979,
 952,
 122,
 71,
 39,
 94,
 132,
 460,
 146,
 625,
 214,
 278,
 667,
 386,
 936,
 643,
 974,
 464,
 995,
 577,
 3,
 186,
 995,
 678,
 882,
 559,
 374,
 554,
 428,
 725,
 96,
 678,
 529,
 374,
 924,
 277,
 606,
 8,
 257,
 397,
 651,
 697,
 486,
 888,
 756,
 399,
 4

In [21]:
np.sum(numbers)

540025

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ...,
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]])