In [4]:
import numpy as np

In [3]:
#times = [7,  15 ,  30]
#distances = [9  ,40 , 200]

In [2]:
times = [63789468]
distances = [411127420471035]

In [32]:
def potential_dist(time):
    charge_times = np.arange(time)
    remaining_time = time - charge_times

    d = charge_times * remaining_time
    return d
    

In [33]:
n_wins = []
start = 1
for t,d in zip(times, distances):
    pd = potential_dist(t)
    n_wins.append(np.where(pd > d)[0].size)
    start *= n_wins[-1]

In [34]:
start

49240091

(array([2, 3, 4, 5]),)

In [7]:
# ok, and via Quadratic Equation

charge_time1 = (-times[0] + np.sqrt(times[0]**2 -4*distances[0] ))/(-2.)
charge_time2 = (-times[0] - np.sqrt(times[0]**2 -4*distances[0] ))/(-2.)

In [11]:
np.floor(charge_time2) - np.floor(charge_time1) 

49240091.0

In [12]:
times = np.array([7,  15 ,  30])
distances =  np.array([9  ,40 , 200])

In [13]:
charge_time1 = (-times + np.sqrt(times**2 -4*distances ))/(-2.)
charge_time2 = (-times - np.sqrt(times**2 -4*distances ))/(-2.)
np.floor(charge_time2) - np.floor(charge_time1) 

array([ 4.,  8., 10.])

In [14]:
charge_time1

array([ 1.69722436,  3.46887113, 10.        ])

In [15]:
charge_time2

array([ 5.30277564, 11.53112887, 20.        ])

In [16]:
# ahh, if it is an exact tie, need to subtract one from the possible wins